name: 'Lint'
on: ['push', 'pull_request']

jobs:
  lint:
    name: 'Run ESLint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Cache node packages'
        uses: 'actions/cache@v4'
        with:
          path: '~/.npm'
          key: "${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/actions/check-version/package-lock.json') }}"
      - name: 'Run ESLint for setup-vim'
        run: |
          npm ci
          npm run --silent lint
      - name: 'Run ESLint for check-version'
        if: 'always()'
        working-directory: '.github/actions/check-version'
        run: |
          npm ci
          npm run --silent lint
