name: 'Test'
on: ['push', 'pull_request']

jobs:
  setup-actions:
    name: 'Setup actions'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Cache node packages'
        uses: 'actions/cache@v2'
        with:
          path: '~/.npm'
          key: "${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/actions/check-version/package-lock.json') }}"
      - name: 'Build actions'
        run: |
          npm ci
          npm run --silent build -- --mode=production
          mkdir -p ${GITHUB_WORKSPACE}/actions/setup-vim
          cp action.js action.yml ${GITHUB_WORKSPACE}/actions/setup-vim

          cd ${GITHUB_WORKSPACE}/.github/actions/check-version
          npm ci
          npm run --silent build
          mkdir -p ${GITHUB_WORKSPACE}/actions/check-version
          cp action.js action.yml ${GITHUB_WORKSPACE}/actions/check-version
      - name: 'Upload actions as artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'actions'
          path: 'actions'
      - name: 'Show GitHub API rate limit'
        run: |
          wget --method=GET \
          --quiet --content-on-error \
          --output-document=- \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          'https://api.github.com/rate_limit'

  test:
    name: '${{ matrix.gui_cui }}/${{ matrix.dl_bd }}: ${{ matrix.vim_type }} ${{ matrix.vim_version }} on ${{ matrix.platform }}'
    strategy:
      matrix:
        vim_type: ['Vim', 'Neovim', 'MacVim']
        vim_version: ['head', 'latest', 'stable']
        platform: ['Linux', 'MacOS', 'Windows']
        gui_cui: ['GUI', 'CUI']
        dl_bd: ['DL', 'AT', 'BD']

        include:
          - platform: 'Linux'
            os: 'ubuntu-latest'
          - platform: 'MacOS'
            os: 'macos-latest'
          - platform: 'Windows'
            os: 'windows-latest'
          - gui_cui: 'GUI'
            gui: 'yes'
          - gui_cui: 'CUI'
            gui: 'no'
          - dl_bd: 'DL'
            download: 'always'
          - dl_bd: 'AT'
            download: 'available'
          - dl_bd: 'BD'
            download: 'never'
          - vim_type: 'Vim'
            vim_version: 'latest'
            version: 'v8.2.0000'
          - vim_type: 'Vim'
            vim_version: 'stable'
            version: 'v8.1.0001'
          - vim_type: 'Neovim'
            vim_version: 'latest'
            version: 'v0.5.1'
          - vim_type: 'MacVim'
            vim_version: 'latest'
            version: 'snapshot-162'  # v8.2.0319
          - vim_type: 'MacVim'
            vim_version: 'stable'
            version: 'snapshot-159'  # v8.1.2168

        exclude:
          # AppImage does not support in old Vim
          - vim_type: 'Vim'
            platform: 'Linux'
            dl_bd: 'DL'
            vim_version: 'stable'
          # DL Vim on MacOS is unavailable
          - vim_type: 'Vim'
            platform: 'MacOS'
            dl_bd: 'DL'
          # Building Neovim v0.4.3 and before versions on MacOS will be failure.
          - vim_type: 'Neovim'
            platform: 'MacOS'
            dl_bd: 'BD'
            vim_version: 'latest'
          - vim_type: 'Neovim'
            platform: 'MacOS'
            dl_bd: 'BD'
            vim_version: 'stable'
          # GUI version of Neovim is unavailable (also skip on Windows)
          - vim_type: 'Neovim'
            gui_cui: 'GUI'
          # Build Neovim on Windows is not supported yet
          - vim_type: 'Neovim'
            platform: 'Windows'
            dl_bd: 'BD'
          # GUI version of MacVim is unavailable
          - platform: 'MacOS'
            gui_cui: 'GUI'
          # MacVim is available only on MacOS
          - vim_type: 'MacVim'
            platform: 'Linux'
          - vim_type: 'MacVim'
            platform: 'Windows'
      fail-fast: false

    needs: 'setup-actions'
    runs-on: '${{ matrix.os }}'
    timeout-minutes: 20
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Download actions'
        uses: 'actions/download-artifact@v2'
        with:
          name: 'actions'
          path: 'actions'
      - name: 'Setup Vim'
        id: 'vim'
        uses: './actions/setup-vim'
        with:
          vim_version: '${{ matrix.version || matrix.vim_version }}'
          vim_type: '${{ matrix.vim_type }}'
          gui: '${{ matrix.gui }}'
          download: '${{ matrix.download }}'
          cache: 'test'
      - name: 'Check Vim version'
        uses: './actions/check-version'
        with:
          expected_vim_version: '${{ steps.vim.outputs.actual_vim_version }}'
          executable: '${{ steps.vim.outputs.executable }}'
          executable_path: '${{ steps.vim.outputs.executable_path }}'
          vim_type: '${{ matrix.vim_type }}'
          gui: '${{ matrix.gui }}'
      - name: 'Delete installed Vim to reinstall'
        if: "matrix.download == 'never'"
        run: |
          rm -fr "${{ steps.vim.outputs.install_path }}"
      - name: 'Setup Vim with cache'
        id: 'vim_with_cache'
        if: "matrix.download == 'never'"
        uses: './actions/setup-vim'
        with:
          vim_version: '${{ matrix.version || matrix.vim_version }}'
          vim_type: '${{ matrix.vim_type }}'
          gui: '${{ matrix.gui }}'
          download: '${{ matrix.download }}'
      - name: 'Check Setup Vim is done with cache'
        if: "matrix.download == 'never'"
        run: |
          if [[ "${{ steps.vim_with_cache.outputs.cache_hit }}" == "true" ]]; then
            echo "Cache hit!"
          else
            echo "Cache not hit..."
            exit 1
          fi

  multiple-test:
    name: 'Install multiple Vims on ${{ matrix.platform }}'
    strategy:
      matrix:
        platform: ['Linux', 'MacOS', 'Windows']

        include:
          - platform: 'Linux'
            os: 'ubuntu-latest'
          - platform: 'MacOS'
            os: 'macos-latest'
          - platform: 'Windows'
            os: 'windows-latest'
      fail-fast: false

    needs: 'setup-actions'
    runs-on: '${{ matrix.os }}'
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Download actions'
        uses: 'actions/download-artifact@v2'
        with:
          name: 'actions'
          path: 'actions'

      - name: 'Setup Vim head'
        id: 'vim_head'
        uses: './actions/setup-vim'
        with:
          vim_version: 'head'
          vim_type: 'Vim'
      - name: 'Setup Vim latest'
        id: 'vim_latest'
        uses: './actions/setup-vim'
        with:
          vim_version: 'v8.2.0000'
          vim_type: 'Vim'
      - name: 'Setup Neovim head'
        id: 'neovim_head'
        uses: './actions/setup-vim'
        with:
          vim_version: 'head'
          vim_type: 'Neovim'
      - name: 'Setup Neovim latest'
        id: 'neovim_latest'
        uses: './actions/setup-vim'
        with:
          vim_version: 'v0.5.0'
          vim_type: 'Neovim'
      - name: 'Setup MacVim head'
        if: "matrix.platform == 'MacOS'"
        id: 'macvim_head'
        uses: './actions/setup-vim'
        with:
          vim_version: 'head'
          vim_type: 'MacVim'
      - name: 'Setup MacVim latest'
        if: "matrix.platform == 'MacOS'"
        id: 'macvim_latest'
        uses: './actions/setup-vim'
        with:
          vim_version: 'snapshot-162'
          vim_type: 'MacVim'

      - name: 'Check Vim head version'
        if: "always() && steps.vim_head.conclusion == 'success'"
        uses: './actions/check-version'
        with:
          expected_vim_version: '${{ steps.vim_head.outputs.actual_vim_version }}'
          executable: '${{ steps.vim_head.outputs.executable }}'
          executable_path: '${{ steps.vim_head.outputs.executable_path }}'
          vim_type: 'Vim'
          use_executable_path: 'yes'
      - name: 'Check Vim latest version'
        if: "always() && steps.vim_latest.conclusion == 'success'"
        uses: './actions/check-version'
        with:
          expected_vim_version: '${{ steps.vim_latest.outputs.actual_vim_version }}'
          executable: '${{ steps.vim_latest.outputs.executable }}'
          executable_path: '${{ steps.vim_latest.outputs.executable_path }}'
          vim_type: 'Vim'
          use_executable_path: 'yes'
      - name: 'Check Neovim head version'
        if: "always() && steps.neovim_head.conclusion == 'success'"
        uses: './actions/check-version'
        with:
          expected_vim_version: '${{ steps.neovim_head.outputs.actual_vim_version }}'
          executable: '${{ steps.neovim_head.outputs.executable }}'
          executable_path: '${{ steps.neovim_head.outputs.executable_path }}'
          vim_type: 'Neovim'
          use_executable_path: 'yes'
      - name: 'Check Neovim latest version'
        if: "always() && steps.neovim_latest.conclusion == 'success'"
        uses: './actions/check-version'
        with:
          expected_vim_version: '${{ steps.neovim_latest.outputs.actual_vim_version }}'
          executable: '${{ steps.neovim_latest.outputs.executable }}'
          executable_path: '${{ steps.neovim_latest.outputs.executable_path }}'
          vim_type: 'Neovim'
          use_executable_path: 'yes'
      - name: 'Check MacVim head version'
        if: "always() && steps.macvim_head.conclusion == 'success'"
        uses: './actions/check-version'
        with:
          expected_vim_version: '${{ steps.macvim_head.outputs.actual_vim_version }}'
          executable: '${{ steps.macvim_head.outputs.executable }}'
          executable_path: '${{ steps.macvim_head.outputs.executable_path }}'
          vim_type: 'MacVim'
          use_executable_path: 'yes'
      - name: 'Check MacVim latest version'
        if: "always() && steps.macvim_latest.conclusion == 'success'"
        uses: './actions/check-version'
        with:
          expected_vim_version: '${{ steps.macvim_latest.outputs.actual_vim_version }}'
          executable: '${{ steps.macvim_latest.outputs.executable }}'
          executable_path: '${{ steps.macvim_latest.outputs.executable_path }}'
          vim_type: 'MacVim'
          use_executable_path: 'yes'


  show-limit-after:
    name: 'Show GitHub API rate limit after test'
    needs: ['test', 'multiple-test']
    runs-on: 'ubuntu-latest'
    timeout-minutes: 1
    if: 'always()'
    steps:
      - name: 'Show GitHub API rate limit'
        run: |
          wget --method=GET \
          --quiet --content-on-error \
          --output-document=- \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          'https://api.github.com/rate_limit'
